### ISSUE TITLE
使用插件gitbook-plugin-anchor-navigation后build报错

### ISSUE THREAD

**Issue by woodsrong** [codepiano/gitbook#2]
1. 增加插件`gitbook-plugin-anchor-navigation`配置
   
   ```
   {
     "plugins": [
         "baiduana",
         "anchor-navigation",
     ]
   }
   ```
2. 执行`gitbook install`安装依赖
3. 再执行`gitbook build`报错如下：
   
   ```
   $ gitbook build
   Starting build ...
   Cannot read property 'children' of undefined
   ```
4. 其他插件，如`gitbook-plugin-tree`也有一些报错

**Comment by codepiano** [comment]
可能是gitbook版本导致，我这个repo停留在1.x，你需要问下插件作者支不支持旧版本

**Comment by woodsrong** [comment]
@codepiano 没有计划升级支持吗

**Comment by codepiano** [comment]
@woodsrong 目前没有，即便要改也是等3.0版本稳定以后直接在3.0版本上支持
